feat: add network api utils for crud operations
prdxn-org/axioned-react-starter pull request #23
Opened 2022-01-10 10:00 UTC by pprathameshaxioned

2022-01-11 10:27 UTC, sharshitprdxn commented on src/utils/Api.js
> +import axios from "axios";
Rename this file to apiUtils

2022-01-11 10:28 UTC, sharshitprdxn commented on src/utils/Api.js
> +export const del = (url) => {
rename the to "delete"

2022-01-11 10:35 UTC, sharshitprdxn commented on src/utils/Api.js
> +    headers: headers ? getHeaders() : {},
if the headers are false, we don't want a new header altogether overriding everything in the application, rather you can do is --- 
{...currentHeader, ...parameterHeaders}

2022-01-11 10:37 UTC, sharshitprdxn commented on src/utils/Api.js
> +
also include handling of the errors throughout... I have sent it on senior-dev channel

2022-01-11 10:38 UTC, sharshitprdxn requested changes
Trying setting in timeouts as well in the req/response objects.

2022-01-12 05:11 UTC, pprathameshaxioned commented on src/utils/Api.js
> +import axios from "axios";
updated!

2022-01-12 05:11 UTC, pprathameshaxioned commented on src/utils/Api.js
> +export const del = (url) => {
updated!

2022-01-12 05:12 UTC, pprathameshaxioned commented on src/utils/Api.js
> +    headers: headers ? getHeaders() : {},
updated!

2022-01-12 06:03 UTC, pprathameshaxioned commented on src/utils/Api.js
> +
changes are done.

2022-01-12 20:02 UTC, sharshitprdxn approved these changes

2022-01-13 05:13 UTC, merged